config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get '/contact', to: 'contact#contact' 
  
  devise_for :users
  resources :events 
  resources :users
  resources :charges

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
    belongs_to :user
    belongs_to :event
  
    validates :stripe_customer_id, presence: true, uniqueness: true
  end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :administrator, class_name: "User"
  
    has_many :attendances, dependent: :destroy 
    has_many :users, through: :attendances 
  
    validates :start_date, presence: true
    validates :duration, presence: true, numericality: { greater_than: 0, only_integer: true, divisible_by: 5 }
    validates :title, presence: true, length: { minimum: 5, maximum: 140 }
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
    validates :location, presence: true
  
    validate :start_date_cannot_be_in_the_past
  
    def start_date_cannot_be_in_the_past
      errors.add(:start_date, "Elle ne peut pas être au passé") if start_date.present? && start_date < Time.zone.now
    end

    def end_date
      start_date + (duration * 60)
    end

    def nombre_inscrit
      attendances.count
    end

    def mail_organisateur
      administrator.email
    end

  end
  

app/models/participation.rb
class Participation < ActiveRecord::Base

belongs_to :event
belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

    has_many :participations, dependent: :destroy
    has_many :attended_events, through: :participations, source: :event
  
    has_many :administrated_events, foreign_key: :administrator_id, class_name: "Event"

    validates_presence_of :email, :encrypted_password

    after_create :welcome_send

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
    

    
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
    def new
    end
    
    def create
      # Amount in cents
      @amount = 500
    
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })
    
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: 'Rails Stripe customer',
        currency: 'usd',
      })
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end


end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def create
        @total = params[:total].to_d
        @session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: [
                {
                    price_data: {
                        currency: 'eur',
                        unit_amount: (@total*100).to_i,
                        product_data: {
                            name: 'Rails Stripe Checkout',
                        },
                    },
                    quantity: 1
                },
            ],
            mode: 'payment',
            success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
            cancel_url: checkout_cancel_url
        )
        redirect_to @session.url, allow_other_host: true
    end
    
    def success
        @session = Stripe::Checkout::Session.retrieve(params[:session_id])
        @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end
    
    def cancel
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def contact

    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    #before_action :authenticate_user!
    
    def index
    
        @events = Event.all
    end

    def show
        
        @event = Event.find(params[:id])
    end

   def new

        @event = Event.new
    end

    

    def create
        
        @event = Event.new(event_params)
        @event.administrator = current_user
        if @event.save
            
            redirect_to @event
        else
            puts @event.errors.full_messages
            render :new
        end
    end
    

    private
    
    def event_params
        params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :desciption, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :desciption, :email, :password, :password_confirmation)}
  end

  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
     @user = current_user
    end

    def update
        @user = User.find(params[:id])
        if @user.update(first_name: params[:user][:first_name], last_name: params[:user][:last_name], description: params[:user][:description])
            puts @user.description
            flash[:notice] = "enregistrer"
            redirect_to user_path(@user.id)
            
        else 
          puts  @user.errors.full_messages
           render :new
        end
    end


    def edit 
        @user = current_user 
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/chekout_helper.rb
module ChekoutHelper
end

app/helpers/contatcts_contoller_helper.rb
module ContatctsContollerHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<!DOCTYPE html>
  <html>
    <head></head>
    <body>
      <%= yield %>
    </body>
  </html>


<%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="500"
            data-locale="auto"></script>
<% end %>

app/views/contact/contact.html.erb
<!-- app/views/contacts/new.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>Contactez-nous</title>
  <!-- Liens vers les fichiers CSS Bootstrap et autres ressources ici -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <style>
    /* Ajoutez votre CSS personnalisé ici */
    .contact-section {
      margin-top: 50px;
    }
    .contact-article {
      display: flex;
      justify-content: space-between;
      margin-top: 20px;
    }
    .contact-info {
      background-color: #f7f7f7;
      padding: 20px;
      border-radius: 5px;
    }
    h3 {
      text-align: center;
    }
    h4 {
      margin-top: 10px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="contact-section">
      <h3>Contact de la team</h3>
      <article class="contact-article">
        <div class="contact-info">
          <p>premier collaborateur :</p>
          <h4>Hamza Bakkar</h4>
          <p>bakkar.hamza92@gmail.com</p>
          <p>01 44 35 35 56</p>
        </div>
        <div class="contact-info">
          <p>deuxième collaboratrice :</p>
          <h4>Aglaë Gourdet</h4>
          <p>a.gourdet.dev@gmail.com</p>
          <p>01 44 35 35 56</p>
        </div>
      </article>
    </div>
  </div>

  <!-- Scripts Bootstrap et autres scripts ici -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

app/views/events/index.html.erb
<div class="container mt-5">


<div class="container mt-5">
  <div class="text-center">
    <h2>Crée un événement !</h2>
    <p class="lead">Balance ton événement via le formulaire ci-dessous</p>
    <%= link_to "Créer un nouvel événement", new_event_path, class: "btn btn-primary" %>
  </div>

<div class="container mt-5">

  <div class="row">
    <% @events.each_with_index do |event, index| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to event.title, event_path(event) %></h5>
            <p class="card-text"><%= event.description %></p>
            <p class="card-text"><strong>Date:</strong> <%= event.start_date.strftime('%B %d, %Y') %></p>
            <p class="card-text"><strong>Lieu:</strong> <%= event.location %></p>
            <p class="card-text"><strong> Prix:</strong> <%= event.price %> €</p>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<%= form_with(model: @event, url: events_path, class: "form mt-4") do |form| %>
    <div class="mb-3">
      <%= form.label :title, "Titre" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :start_date, "Date de début" %>
      <%= form.datetime_select :start_date, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :duration, "Durée (en minutes)" %>
      <%= form.number_field :duration, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :description, "Description" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :price, "Prix" %>
      <%= form.number_field :price, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :location, "Lieu" %>
      <%= form.text_field :location, class: "form-control" %>
    </div>
    <%= form.submit "Créer l'événement", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <h1><%= @event.title %></h1>
  <p><%= @event.description %></p>
  <p><strong>Date de début:</strong> <%= @event.start_date %></p>
  <p><strong>Durée:</strong> <%= @event.duration %> minutes</p>
  <p><strong>Date de fin:</strong> <%= @event.end_date %> </p>
  <p><strong>Nombre d'inscrit:</strong> <%= @event.nombre_inscrit %> </p>
  <p><strong>Lieu:</strong> <%= @event.location %></p>
  <p><strong>Prix:</strong> <%= @event.price %>€ </p>
  <p><strong>Adresse email :</strong> <%= @event.mail_organisateur %> </p>
  
  <% if user_signed_in? %>
    <%= button_to "Passer commande a #{@event.price}€", checkout_create_path(total: @event.price), class: "btn btn-primary", data: {turbo: false} %>
  <% else %>
    <%= button_to "S'inscrire" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
<header class="p-3 bg-dark text-white">
<script src="https://js.stripe.com/v3/"></script>
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 text-secondary">Eventbrite</a></li>
        <li><%= link_to "Evenements", events_path, class: "nav-link px-2 text-white" %></li>
         <li>  <a class="nav-link px-2 text-white" href="/contact">contact </a> </li>
            <% if user_signed_in? %>
      <li>
         <li>  <a class="nav-link px-2 text-white"  href="<%= user_path(current_user) %>"> Mon profil </a> </li>
         <% end %>
      </ul>

    

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          User Actions
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
         <% if user_signed_in? %>
      <li>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete} %>
      </li>

      <li>
        Voici ton email : <%= current_user.email %>
      </li>

      <li>
        <%= link_to "Edit email / password", edit_user_registration_path %>
      </li>

    <% else %>
      <li>    
        <%= link_to "Sign in", new_user_session_path %>
      </li>

      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>

    <% end %>
  </ul>
         
        </ul>
      </div>
    </div>
  </div>
</header>
  
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Votre titre ici</title>
  <!-- Liens vers les fichiers CSS Bootstrap et autres ressources ici -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <!-- Contenu de l'en-tête avec Bootstrap ici -->
    </div>
  </header>

  <div class="container mt-5">
    <h1>Bienvenue sur la page Eventbrite locale</h1>
    <p>Vous trouverez les événements qui pourraient vous intéresser :</p>
    <ul class="list-group">
      <% if user_signed_in? %>
        <li class="list-group-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "btn btn-danger" %>
        </li>

        <li class="list-group-item">
          Voici ton email : <%= current_user.email %>
        </li>

        <li class="list-group-item">
          <%= link_to "Secret page", static_pages_secret_path, class: "btn btn-primary" %>
        </li>

        <li class="list-group-item">
          <%= link_to "Edit email / password", edit_user_registration_path, class: "btn btn-secondary" %>
        </li>

      <% else %>
        <li class="list-group-item">
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %>
        </li>

        <li class="list-group-item">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success" %>
        </li>

      <% end %>
    </ul>
  </div>

  <!-- Scripts Bootstrap et autres scripts ici -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"></script>
</body>
</html>

app/views/static_pages/secret.html.erb
Bienvenue

app/views/users/edit.html.erb
<h1> Editer </h1>
<%= form_for @user do |f| %>


<div class="form-group">
    <label> Modifier first last_name </label>
    <%= f.text_field :first_name, class: 'form-control'%>
</div>

<div class="form-group">
    <label> Modifier last name </label>
    <%= f.text_field :last_name, class: 'form-control'%>
</div>


<div class="form-group">
    <label> titre la description </label>
    <%= f.text_field :description, class: 'form-control'%>
</div>

<div class ="form-group">
     
    <button type="submit"class="btn-btn-primary"> Modifier l'article </button> 
</div>


<% end %>

app/views/users/show.html.erb
 <div style="text-align: center; margin-top : 150px">
 
     <div style="margin-bottom : 30px">
        <h1> Prénom : <%= @user.first_name %> </h1>
        <h1> Nom : <%= @user.last_name %> </h1>
        <h1> Description : <%= @user.description %> </h1>
        <h1> adresse email :  <%= @user.email %> </h1>
        <h1> Description :  <%= @user.description %> </h1>

        <div> <%= link_to "Editer le profil N° #{@user.id}", edit_user_path(@user.id)%> </div>
        <%= button_to "redirection a l'acceuil", root_path, method: :get %>
       
         

    </div>